version: "3.7"
services:
  api:
    image: ${IMG_NAME_API}
    platform: "linux/amd64"
    working_dir: /app
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    env_file: .env
    networks:
      - app
    restart: always
  front:
    image: ${IMG_NAME_FRONT}
    platform: "linux/amd64"
    working_dir: /app
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file: .env
    networks:
      - app
    restart: always

volumes:
  db_data:
  nginx-data:

networks:
  app:
    driver: "bridge"
