name: Deploy front end to github pages
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  VITE_DEFAULT_ORGANIZATION_ID: "racky-team"
  DEFAULT_ORGANIZATION_NAME: "Racky Team"
  DEFAULT_ORGANIZATION_ZONE: "Online"
  AWS_REGION: "eu-west-3"

jobs:
  setup-and-deploy:
    name: Setup & Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install deps (with cache)
        run: pnpm install
      - name: Build
        run: pnpm build:web
      - name: Setup pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/web/dist
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
